
export const eventsOrdered = [
  {
    url: "https://2019.tamudatathon.com/",
    year: 2019,
    logo: "/images/past-logos/TD2019.png",
    lite: false,
    label: "2019 Datathon",
    season: "Fall",
  },
  {
    url: "https://2020.tamudatathon.com/",
    year: 2020,
    logo: "/images/past-logos/TD2020.png",
    lite: false,
    label: "2020 Datathon",
    season: "Fall",
  },
  {
    url: "https://2021.tamudatathon.com/",
    year: 2021,
    logo: "/images/past-logos/TD2021.png",
    lite: false,
    label: "2021 Datathon",
    season: "Fall",
  },
  {
    url: "https://2022.tamudatathon.com/",
    year: 2022,
    logo: "/images/past-logos/TD2022.png",
    lite: false,
    label: "2022 Datathon",
    season: "Fall",
  },
  {
    url: "https://2023.tamudatathon.com/",
    year: 2023,
    logo: "/images/past-logos/TD2023.png",
    lite: false,
    label: "2023 Datathon",
    season: "Fall",
  },
  {
    url: "https://2023-lite.tamudatathon.com/",
    year: 2023,
    logo: "/images/past-logos/TD2023.png",
    lite: true,
    label: "2023 Lite Datathon",
    season: "Spring",
  },
  {
    url: "https://2024.tamudatathon.com/",
    year: 2024,
    logo: "/images/past-logos/TD2024.png",
    lite: false,
    label: "2024 Datathon",
    season: "Fall",
  },
  {
    url: "https://2025-lite.tamudatathon.com/",
    year: 2025,
    logo: "/images/past-logos/TD-LITE2025.webp",
    lite: true,
    label: "2025 Lite Datathon",
    season: "Spring",
  },
  {
    url: "https://2025.tamudatathon.com/",
    year: 2025,
    logo: "/images/past-logos/TD2025.png",
    lite: false,
    label: "2025 Datathon",
    season: "Fall",
  },
  {
    url: "https://2026-lite.tamudatathon.com/",
    year: 2026,
    logo: "/images/past-logos/TD2026.png",
    lite: true,
    label: "2026 Lite Datathon",
    season: "Spring",
  },
];
