name: Typecheck, lint, format, and fix
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    defaults:
      run:
        working-directory: ./my-turborepo
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ./my-turborepo
    - name: Install dependencies
      run: pnpm install
    - name: Typecheck
      run: pnpm typecheck
    - name: Fix linting issues
      run: pnpm lint:fix
    - name: Fix formatting issues
      run: pnpm format:fix
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      
